### ISSUE TITLE
Верхняя панель (TopBar)

### ISSUE THREAD

**Issue by drxwat** [drxwat/godoshka-quiz-admin-panel#8]
Панель, где выводится имя авторизованого пользователя и кнопка "Выйти"

Панель видна только в авторизованых роутах

Hint: В данный момент корневым модулем навигации после авторизации является modules т.к. react-router связывает его с роутом /. Необходимо создать отдельный компонент аля Application и связать его с /. Туда добавить панель, навигацию и <Outlet/>. После чего настроить дочерние роуты: модули, вопросы и т.д. Модули будут роутом по умолчанию

**Comment by RenatMardanov** [comment]
Сделаю, то есть это будет просто компонент который мы прокинем в места где мы уже прологинены? а не будет сверяться с токеном для отображения верно?

**Comment by RenatMardanov** [comment]
Done

**Comment by RenatMardanov** [comment]
Done
