### ISSUE TITLE
Таблица модулей

### ISSUE THREAD

**Issue by drxwat** [drxwat/godoshka-quiz-admin-panel#9]
Вывести реальный споско модулей в таблице, используя supabase API. 

Код

`await client.from('modules').select()`

Дока https://supabase.com/docs/reference/javascript/select

Hint: понадобится useEffect т.к. просто так дернуть промис в компоненте с хуками не выйдет

**Comment by RenatMardanov** [comment]
Это я тоже примерно знаю как делать, делаю просто через fetch? Ты аксиос тащить не собираешься?

**Comment by RenatMardanov** [comment]
done
